### ISSUE TITLE
disable digital buffer on pins AIN0 && AIN1 to reduce current consumption

### ISSUE THREAD

**Issue by ami2go** [leomil72/analogComp#8]
Hello. Not a big issue. Library works well thank you for your work! 
I was looking thought code and didn't undestand how one things works. 
May be i didn't understand just you code. 
Look at section of DIDR0 register (digital input disable)
```
#if defined(ATTINYx5)
	DIDR0 &= ~((1<<AIN1D) | (1<<AIN0D));
#elif defined(ATTINYx4)
	DIDR0 &= ~((1<<ADC2D) | (1<<ADC1D));
#elif defined (ATMEGAx4)
	DIDR1 &= ~(1<<AIN0D);
#elif defined (ATTINYx313)
	DIDR &= ~((1<<AIN1D) | (1<<AIN0D));
#elif defined (ATMEGAx8) || defined(ATMEGAx4) || defined(ATMEGAx0)
    DIDR1 &= ~((1<<AIN1D) | (1<<AIN0D));
#endif
```
It looks like you writing "0" while datasheets says it have to be "1" (Attiny24 page 117)

> When this bit is written **logical one**, **the digital input buffer on the AIN1/0 pin is disabled**. The corresponding PIN register bit  will always read as zero when this bit is set. When an analog signal is applied to the AIN1/0 pin and the digital input from this pin is not needed, **this bit should be written logical one to reduce power consumption in the digital input buffer**.
>

**Comment by leomil72** [comment]
I inverted the code to enable/disable digital buffers. Thanks for the notification. Fixed in 1.2.4
